### ISSUE TITLE
Feature request: add alias for the 'unicode-1-1-utf-7' charset

### ISSUE THREAD

**Issue by speller** [zetacomponents/Mail#41]
Some linux systems have no support for this encoding, but emails with it is still present. For example, the Hotmail mail delivery daemon report emails. Message parsing become broken with PHP Notice:

> iconv(): Wrong charset, conversion from `unicode-1-1-utf-7' to `utf-8' is not allowed`

I suggest to add the hardcoded alias to the ezcMailCharsetConverter::convertToUTF8Iconv() method:

        if ( $originalCharset === 'unknown-8bit' || $originalCharset === 'x-user-defined' )
        {
            $originalCharset = "latin1";
        } 
        elseif ( $originalCharset === 'unicode-1-1-utf-7')
        {
            $originalCharset = "utf7";
        }

**Comment by derickr** [comment]
Hi!

We are aware that there are many weird mail servers out there. We can not possible implement hacks for all weird things mail servers do, that's why we made it possible to override things like the character set conversion. 

We have a section in our tutorial to explain how to do this: http://zetacomponents.org/documentation/trunk/Mail/tutorial.html#parsing-iconv-notices

In your case, you want to create a new class "myMailCharsetConvertor" implementing the following static method:

```
class myMailCharsetConverter
{
     public static function convertToUTF8WithHotmailHack( $text, $originalCharset )
     {
         if ( $originalCharset === 'unknown-8bit' || $originalCharset === 'x-user-defined' )
         {
             $originalCharset = "latin1";
         }
         if ( $originalCharset === 'unicode-1-1-utf-7' )
         {
             $originalCharset = "utf7";
         }
         return iconv( $originalCharset, 'utf-8', $text );
     }
}
```

Then before you run the mail parser, include the following in your code:

```
ezcMailCharsetConverter::setConvertMethod( array( 'myMailCharsetConvertor', 'convertToUTF8WithHotmailHack' ) );
```

cheers,
Derick

**Comment by speller** [comment]
Don't understand what's problem to have an array of mappings of such encodings. To prevent many users to have the same problems. But it is your right to decide what to do.

I created this issue because some implementations of the iconv library support this encoding, some not.  If based on libiconv - will support. If based on glibc - will not support. So your code will work dirrerently on different servers. That's not good in my opinion.
