### ISSUE TITLE
.msg attachment

### ISSUE THREAD

**Issue by ggiacomoo** [zetacomponents/Mail#75]
is it possible to parse mail to leave "as it is"  the ".msg" attachment!? 
instead of "inspecting it inside" ???

**Comment by derickr** [comment]
I don't understand what you mean. Can you elaborate? Particularly with a code snippet and full email source.

**Comment by ggiacomoo** [comment]
if i save a mail from outlook  it create a file with .msg extension (maybe it has its own attached pdf images etc...),
i attach the ".msg" file to mail and send...

when i fetch mail with zetacomponentMail, there is no ".msg" attachment, and i see something "inside"

example email with msg and pdf inside https://ufile.io/kzi8vb6k

**Comment by derickr** [comment]
The Mail package doesn't support the `.msg` format at all, it is an [open format](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxmsg/b046868c-9fbf-41ae-9ffb-8de2bd4eec82) by Microsoft (now). It is also not a format that email servers return.

When reading an email from a server, the Mail component will unpack the full email, including attachments, so that you can read the data in them. I don't think there is currently a way to disable that. It would also not make sense, because the whole purpose of reading and fetching email is that you can see what's inside.

You can use the mail class's [generateHeaders](http://zetacomponents.org/documentation/trunk/Mail/phpdoc/ezcMail.html#generateHeaders) and [generateBody](http://zetacomponents.org/documentation/trunk/Mail/phpdoc/ezcMail.html#generateBody) methods to rebuild the email as it was retrieved from the server, but this will not be the exact same data.

**Comment by ggiacomoo** [comment]
ok, many thanks, i'll try the generateHeaders and generateBody methods as soon possible.
just for now i've done a custom handling over type/subtype to create a file .eml "similar" to .msg
